import { useState } from 'react';
import PaperRocketSVG from './PaperRocketSVG';

export default function ItineraryDrawer({ isOpen, onClose, itineraryText, destination }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(itineraryText || '');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-hidden">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-950/70 backdrop-blur-sm transition-opacity animate-in fade-in duration-300"
        onClick={onClose}
      />

      <div className="fixed inset-y-0 right-0 max-w-full flex pl-10">
        <div className="w-screen max-w-2xl bg-slate-900/95 backdrop-blur-2xl border-l border-white/10 shadow-2xl text-slate-100 flex flex-col animate-in slide-in-from-right duration-500">
          
          {/* Drawer Header */}
          <div className="px-6 py-5 border-b border-white/10 flex items-center justify-between bg-slate-900/80 sticky top-0 z-10">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-teal-400 to-indigo-500 flex items-center justify-center shadow-lg shadow-teal-500/20">
                <PaperRocketSVG className="w-7 h-7 transform -rotate-12" />
              </div>
              <div>
                <h2 className="font-sans text-xl font-bold text-teal-300 tracking-tight flex items-center gap-2">
                  <span>{destination ? `${destination} Itinerary` : 'Complete Travel Itinerary'}</span>
                  <PaperRocketSVG className="w-5 h-5 inline transform -rotate-12" />
                </h2>
                <p className="text-xs text-slate-400 font-medium">Multi-Agent Synthesized Travel Plan</p>
              </div>
            </div>

            <div className="flex items-center gap-3">
              <button
                onClick={handleCopy}
                className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-xs font-semibold text-teal-300 transition-all border border-white/10 flex items-center gap-1.5"
              >
                {copied ? '✓ Copied!' : '📋 Copy Itinerary'}
              </button>
              <button
                onClick={onClose}
                className="w-9 h-9 rounded-xl bg-white/10 hover:bg-white/20 flex items-center justify-center text-slate-300 hover:text-white transition-all border border-white/10 text-lg"
              >
                ✕
              </button>
            </div>
          </div>

          {/* Drawer Content */}
          <div className="flex-1 overflow-y-auto p-6 sm:p-8 space-y-6 scroll-smooth">
            <div className="prose prose-invert prose-teal max-w-none">
              <div className="whitespace-pre-wrap leading-relaxed text-[15px] font-sans text-slate-200">
                {itineraryText}
              </div>
            </div>
          </div>

          {/* Drawer Footer */}
          <div className="px-6 py-4 border-t border-white/10 bg-slate-900/90 flex items-center justify-between text-xs text-slate-400">
            <span>✨ Generated by WanderWise Multi-Agent System</span>
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-gradient-to-r from-teal-500 to-indigo-600 text-white font-semibold shadow-md hover:brightness-110 transition-all"
            >
              Close Panel
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
